# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.cache/wt [current_project]
set_property parent.project_path C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/global.v
set_property file_type "Verilog Header" [get_files C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/global.v]
read_verilog -library xil_defaultlib -sv {
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/model/bhvsram/bhv_1w1r_sram.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/cnn.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/draw_rectangle.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/lenet.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/lenet_roms.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/osd.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/model/xilinx/xilinx_1w1r_sram.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/top/lenet_top.v
}
read_verilog -library xil_defaultlib {
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/capture.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/src/misc.v
  C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/imports/cnn_open/model/xilinx/xilinx_srams.v
}
read_ip -quiet C:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/ip/pll_main/pll_main.xci
set_property used_in_implementation false [get_files -all c:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/ip/pll_main/pll_main_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/ip/pll_main/pll_main.xdc]
set_property used_in_implementation false [get_files -all c:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/ip/pll_main/pll_main_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/AmirHasan/Desktop/DSDProject/cnn/cnn.srcs/sources_1/ip/pll_main/pll_main_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xcku040-ffva1156-2-e -max_dsp 0


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
